"""Initial schema - create player_stats table

Revision ID: f143eac7c6ad
Revises: 
Create Date: 2026-04-27 00:28:15.796459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f143eac7c6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbrefid', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_player_stats_bbrefid_year', 'player_stats', ['bbrefid', 'year'], unique=True)
    op.create_index(op.f('ix_player_stats_bbrefid'), 'player_stats', ['bbrefid'], unique=False)
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_year'), 'player_stats', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_year'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_bbrefid'), table_name='player_stats')
    op.drop_index('idx_player_stats_bbrefid_year', table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
